Repository jsyiek/AU2, pull requests merged in 2024-11, with the labels that each got.

#52 [38] Emails plugin improvements, refactor of components
  AU2/database/AssassinsDatabase.py
  AU2/frontends/inquirer_cli.py
  AU2/html_components/DependentComponents/AssassinDependentCrimeEntry.py
  AU2/html_components/DependentComponents/AssassinDependentFloatEntry.py
  AU2/html_components/DependentComponents/AssassinDependentIntegerEntry.py
  AU2/html_components/DependentComponents/AssassinDependentKillEntry.py
  AU2/html_components/DependentComponents/AssassinDependentReportEntry.py
  AU2/html_components/DependentComponents/AssassinDependentSelector.py
  AU2/html_components/DependentComponents/AssassinDependentTextEntry.py
  AU2/html_components/DependentComponents/AssassinPseudonymPair.py
  AU2/html_components/DependentComponents/__init__.py
  AU2/html_components/MetaComponents/Dependency.py
  AU2/html_components/MetaComponents/__init__.py
  AU2/html_components/SimpleComponents/ArbitraryList.py
  AU2/html_components/SimpleComponents/Checkbox.py
  AU2/html_components/SimpleComponents/DatetimeEntry.py
  AU2/html_components/SimpleComponents/DefaultNamedSmallTextbox.py
  AU2/html_components/SimpleComponents/EmailSelector.py
  AU2/html_components/SimpleComponents/HiddenTextbox.py
  AU2/html_components/SimpleComponents/InputWithDropDown.py
  AU2/html_components/SimpleComponents/IntegerEntry.py
  AU2/html_components/SimpleComponents/Label.py
  AU2/html_components/SimpleComponents/LargeTextEntry.py
  AU2/html_components/SimpleComponents/NamedSmallTextbox.py
  AU2/html_components/SimpleComponents/PathEntry.py
  AU2/html_components/SimpleComponents/SelectorList.py
  AU2/html_components/SimpleComponents/__init__.py
  AU2/plugins/CorePlugin.py
  AU2/plugins/custom_plugins/CompetencyPlugin.py
  AU2/plugins/custom_plugins/LocalBackupPlugin.py
  AU2/plugins/custom_plugins/MafiaPlugin.py
  AU2/plugins/custom_plugins/PageGeneratorPlugin.py
  AU2/plugins/custom_plugins/PlayerImporterPlugin.py
  AU2/plugins/custom_plugins/PolicePlugin.py
  AU2/plugins/custom_plugins/RandomGamePlugin.py
  AU2/plugins/custom_plugins/SRCFPlugin.py
  AU2/plugins/custom_plugins/TargetingPlugin.py
  AU2/plugins/custom_plugins/WantedPlugin.py
  AU2/plugins/util/PoliceRankManager.py
Labels: enhancement, tech debt

#49 [4] Store datetime that each pseudonym is added, in order to render [DX] non-anachronistically
  .idea/dbnavigator.xml
  AU2/database/model/Assassin.py
  AU2/frontends/inquirer_cli.py
  AU2/html_components/SimpleComponents/ArbitraryList.py
  AU2/html_components/SpecialComponents/EditablePseudonymList.py
  AU2/html_components/SpecialComponents/__init__.py
  AU2/plugins/CorePlugin.py
  AU2/plugins/custom_plugins/PageGeneratorPlugin.py
Labels: bug, tech debt

#51 [19] Escaped {} in inquirer arguments
  AU2/frontends/inquirer_cli.py
  AU2/html_components/SimpleComponents/LargeTextEntry.py
  AU2/plugins/util/game.py
Labels: bug

#48 Print using labels in TargetingPlugin
  AU2/plugins/custom_plugins/TargetingPlugin.py
  AU2/test/plugins/util/custom_plugins/test_TargetingPlugin.py
Labels: tech debt

#56 [55] Make assassins searchable
  AU2/frontends/inquirer_cli.py
  AU2/html_components/HTMLComponent.py
  AU2/html_components/MetaComponents/ComponentOverride.py
  AU2/html_components/MetaComponents/Searchable.py
  AU2/html_components/SimpleComponents/SelectorList.py
  AU2/plugins/custom_plugins/UIConfigPlugin.py
Labels: enhancement

#58 [57] Display datetimes in event selector of Event -> Update
  AU2/database/model/Assassin.py
  AU2/plugins/CorePlugin.py
Labels: enhancement

#61 [60] Bounty plugin
  AU2/plugins/CorePlugin.py
  AU2/plugins/custom_plugins/BountyPlugin.py
  AU2/plugins/custom_plugins/TargetingPlugin.py
  AU2/plugins/custom_plugins/html_templates/bounties.html
Labels: enhancement

#59 [44] Added Assassin -> Hide export
  AU2/database/AssassinsDatabase.py
  AU2/database/model/Assassin.py
  AU2/frontends/inquirer_cli.py
  AU2/plugins/CorePlugin.py
  AU2/plugins/custom_plugins/SRCFPlugin.py
  AU2/plugins/custom_plugins/UIConfigPlugin.py
Labels: enhancement

#69 [63] Assassin -> Resurrect as Police
  AU2/database/AssassinsDatabase.py
  AU2/database/model/Assassin.py
  AU2/plugins/CorePlugin.py
  AU2/plugins/custom_plugins/PolicePlugin.py
  AU2/test/plugins/util/custom_plugins/test_PolicePlugin.py
  AU2/test/test_utils.py
Labels: bug, enhancement

#76 [62] Improved Competency -> Show deadlines [REQUIRES `tabulate`]
  AU2/frontends/inquirer_cli.py
  AU2/html_components/SimpleComponents/Table.py
  AU2/plugins/custom_plugins/BountyPlugin.py
  AU2/plugins/custom_plugins/CompetencyPlugin.py
  AU2/plugins/custom_plugins/html_templates/bounties.html
  AU2/plugins/util/CompetencyManager.py
  requirements.txt
Labels: enhancement

#78 [75] Added PgUp, PgDown, Home and End key support
  .gitignore
  AU2/frontends/inquirer_cli.py
  AU2/plugins/util/ScoreManager.py
Labels: enhancement

#77 [53] notepad via pyinquirer on windows uses utf-8 by default
  AU2/__init__.py
Labels: bug

#87 Small changes
  AU2/__init__.py
  AU2/plugins/custom_plugins/CompetencyPlugin.py
  AU2/plugins/custom_plugins/SRCFPlugin.py
  AU2/plugins/custom_plugins/ScoringPlugin.py
  AU2/plugins/custom_plugins/WantedPlugin.py
  AU2/test/plugins/util/custom_plugins/test_CompetencyPlugin.py
Labels: bug, enhancement

#86 [82] Add encoding info (utf-8) to email headers
  AU2/plugins/custom_plugins/SRCFPlugin.py
Labels: bug

#84 [80] Sanity checking framework
  AU2/plugins/CorePlugin.py
  AU2/plugins/sanity_checks/MissingHtmlSpecifier.py
  AU2/plugins/sanity_checks/__init__.py
  AU2/plugins/sanity_checks/model/SanityCheck.py
  AU2/plugins/sanity_checks/model/__init__.py
  AU2/plugins/util/game.py
Labels: enhancement

#83 Implemented `DangerousConfigExport`
  AU2/frontends/inquirer_cli.py
  AU2/html_components/SpecialComponents/ConfigOptionsList.py
  AU2/plugins/AbstractPlugin.py
  AU2/plugins/CorePlugin.py
  AU2/plugins/custom_plugins/CompetencyPlugin.py
  AU2/plugins/custom_plugins/TargetingPlugin.py
  requirements.txt
Labels: enhancement
