Repository jsyiek/AU2, pull requests merged in 2024-10, with the labels that each got.

#30 Testing framework
  AU2/database/AssassinsDatabase.py
  AU2/database/EventsDatabase.py
  AU2/database/GenericStateDatabase.py
  AU2/database/model/Assassin.py
  AU2/database/model/PersistentFile.py
  AU2/plugins/CorePlugin.py
  AU2/plugins/custom_plugins/TargetingPlugin.py
  AU2/plugins/util/game.py
  AU2/plugins/util/random_data.py
  AU2/test/__init__.py
  AU2/test/plugins/__init__.py
  AU2/test/plugins/util/__init__.py
  AU2/test/plugins/util/custom_plugins/__init__.py
  AU2/test/plugins/util/custom_plugins/test_CompetencyPlugin.py
  AU2/test/plugins/util/custom_plugins/test_LocalBackupPlugin.py
  AU2/test/plugins/util/custom_plugins/test_TargetingPlugin.py
  AU2/test/test_utils.py
Labels: tech debt

#32 Wanted rewrite
  AU2/frontends/__init__.py
  AU2/frontends/au2_packager.py
  AU2/plugins/custom_plugins/PolicePlugin.py
  AU2/plugins/custom_plugins/WantedPlugin.py
  AU2/plugins/custom_plugins/html_templates/wanted.html
  AU2/plugins/util/DeathManager.py
  AU2/plugins/util/PoliceRankManager.py
  AU2/plugins/util/WantedManager.py
Labels: enhancement, tech debt

#47 [BUG] Double deaths cause `TargetingPlugin.compute_targets` to crash
  AU2/plugins/custom_plugins/TargetingPlugin.py
Labels: bug
