Repository jsyiek/AU2, pull requests merged in 2025-02, with the labels that each got.

#100 [73] Stats Page
  AU2/__init__.py
  AU2/database/model/Assassin.py
  AU2/frontends/inquirer_cli.py
  AU2/plugins/custom_plugins/CompetencyPlugin.py
  AU2/plugins/custom_plugins/PageGeneratorPlugin.py
  AU2/plugins/custom_plugins/ScoringPlugin.py
  AU2/plugins/custom_plugins/html_templates/stats.html
  AU2/plugins/util/ScoreManager.py
  AU2/plugins/util/date_utils.py
  requirements.txt
Labels: enhancement

#101 [74] Allow frequently-used Exports to be pinned for ease of use
  AU2/frontends/inquirer_cli.py
  AU2/plugins/CorePlugin.py
Labels: usability

#105 [EBF] Missing fields in CorePlugin.on_assassin_update
  AU2/plugins/CorePlugin.py
Labels: bug

#110 Include pseudonym index in `EditablePseudonymList`
  AU2/frontends/inquirer_cli.py
Labels: usability

#109 [102] [SRCFPlugin] Auto-backups and remote backup sorting
  .idea/misc.xml
  AU2/plugins/CorePlugin.py
  AU2/plugins/custom_plugins/SRCFPlugin.py
Labels: enhancement

#111 [92] Sanity check for when player not dead but [DX] or [NX] used.
  AU2/plugins/sanity_checks/PlayerNotDead.py
  AU2/plugins/sanity_checks/__init__.py
Labels: usability

#113 Don't include hidden police on police page
  AU2/plugins/custom_plugins/PolicePlugin.py
Labels: bug
